### PR TITLE
fix(#2794): sshfs compatibility

### LINKED ISSUE #2794: `nvim-tree` allows the creation of files over `sshfs`, but they can't be accessed
### Description

I'm using `nosduco/remote-sshfs.nvim` to work remotely over sshfs.

`nvim-tree` doesn't show anything from the mounted folder on the server, however, you can perform edit operations from `nvim-tree` directly, such as creating a new file (see image, I basically pressed `a` on top of the folder in nvim-tree panel).

I checked on server and the file was indeed created.

Thanks

### Neovim version

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478


"nvim-tree.lua": { "branch": "master", "commit": "517e4fbb9ef3c0986da7047f44b4b91a2400f93c" }
```

### Operating system and version

macOS Sonoma 14.5 (23F79)

### Windows variant

_No response_

### nvim-tree version

{ "branch": "master", "commit": "517e4fbb9ef3c0986da7047f44b4b91a2400f93c" }

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
    "wbthomason/packer.nvim",
    "nvim-tree/nvim-tree.lua",
    "nvim-tree/nvim-web-devicons",
    -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    'nosduco/remote-sshfs.nvim',
    "nvim-telescope/telescope.nvim", branch = "0.1.x",
    "nvim-lua/plenary.nvim",
    },

    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
    require("nvim-tree").setup {}
    require('remote-sshfs').setup {
      connections = {
        ssh_configs = { -- which ssh configs to parse for hosts list
          vim.fn.expand "$HOME" .. "/.ssh/config",
          "/etc/ssh/ssh_config",
        },
        sshfs_args = { -- arguments to pass to the sshfs command
          "-o reconnect",
          "-o auto_cache",
          "-o Ciphers=aes128-ctr",
          "-o ConnectTimeout=5",
          "-C",
          "-o cache_timeout=60",
          "-o cache=yes",
        },
      },
      mounts = {
        base_dir = vim.fn.expand "$HOME" .. "/.sshfs/", -- base directory for mount points
        unmount_on_exit = true, -- run sshfs as foreground, will unmount on vim exit
      },
      handlers = {
        on_connect = {
          change_dir = true, -- when connected change vim working directory to mount point
        },
        on_disconnect = {
          clean_mount_folders = false, -- remove mount point folder on disconnect/unmount
        },
        on_edit = {}, -- not yet implemented
      },
      ui = {
        select_prompts = false, -- not yet implemented
        confirm = {
          connect = true, -- prompt y/n when host is selected to connect to
          change_dir = false, -- prompt y/n to change working directory on connection (only applicable if handlers.on_connect.change_dir is enabled)
        },
      },
      log = {
        enable = false, -- enable logging
        truncate = false, -- truncate logs
        types = { -- enabled log types
          all = false,
          util = false,
          handler = false,
          sshfs = false,
        },
      },
    }
    require('telescope').setup {}

end

-- UNCOMMENT this block for diagnostics issues, substituting pattern and cmd as appropriate.
-- Requires diagnostics.enable = true in setup.
--[[
vim.api.nvim_create_autocmd("FileType", {
  pattern = "lua",
  callback = function()
    vim.lsp.start { cmd = { "lua-language-server" } }
  end,
})
]]
```

### Steps to reproduce

```
1. nvim -nu /tmp/nvt-min.lua
2. :RemoteSSHFSConnect (pick server; have it listed in your ~/.ssh/config)
3. :NvimTreeOpen
4. expand the mounted folder (should be ~ on your server)
```

### Expected behavior

List all files, directories, normal navigation as one would have locally.

### Actual behavior

image

### PR DESCRIPTION
**Pull request by mxple**
fixes #2794

Re-add sshfs compatibility. Update to use `fs_lstat` instead of `fs_stat` so symlinks aren't automatically followed.

### CODE REVIEW

**Comment by mxple** [comment]
We may need to update `---@type uv.fs_stat.result|nil` to reflect the correct type.

**Comment by alex-courtis** [comment]
Looks good. Instrumenting shows no mismatch on lstat, mismatch when changed back to stat:

```
      log.line("dev", "reload            %s t = %s type = %s abs = %s", t == type and "OK      " or "MISMATCH", t, type, abs)
```

```
        log.line("dev", "populate_children %s t = %s type = %s abs = %s", t == type and "OK      " or "MISMATCH", t, type, abs)
```

File: lua/nvim-tree/explorer/init.lua [hunk 1]
```diff
@@ -151,11 +154,11 @@ function Explorer:reload(node, git_status)
 
       if not nodes_by_path[abs] then
         local new_child = nil
-        if t == "directory" and vim.loop.fs_access(abs, "R") and Watcher.is_fs_event_capable(abs) then
+        if type == "directory" and vim.loop.fs_access(abs, "R") and Watcher.is_fs_event_capable(abs) then
```
Comment (alex-courtis) [inline lua/nvim-tree/explorer/init.lua:157]: To avoid any future refactor/rebase fails, and to keep git history simple, please rename `type` to `t`

File: lua/nvim-tree/actions/fs/remove-file.lua [hunk 2]
```diff
@@ -57,13 +57,18 @@ local function remove_dir(cwd)
...
+    local name, _ = vim.loop.fs_scandir_next(handle)
     if not name then
       break
     end
 
     local new_cwd = utils.path_join { cwd, name }
-    if t == "directory" then
+
+    -- Type must come from fs_stat and not fs_scandir_next to maintain sshfs compatibility
+    local stat = vim.loop.fs_stat(new_cwd)
```
Comment (alex-courtis) [inline lua/nvim-tree/actions/fs/remove-file.lua:68]: Should this be fs_lstat?

File: lua/nvim-tree/explorer/init.lua [hunk 3]
```diff
@@ -238,17 +241,17 @@ function Explorer:refresh_parent_nodes_for_path(path)
...
+        return node.nodes
+      end)
+      :applier(function(node)
+        local abs_contains = node.absolute_path and path:find(node.absolute_path, 1, true) == 1
+        local link_contains = node.link_to and path:find(node.link_to, 1, true) == 1
+        if abs_contains or link_contains then
+          table.insert(parent_nodes, node)
+        end
+      end)
+      :iterate()
```
Comment (alex-courtis) [inline lua/nvim-tree/explorer/init.lua:254]: Unnecessary whitespace change.

You can `make style-fix`

**Review by alex-courtis — CHANGES_REQUESTED** [review]
This is looking good; great find on `lstat`!

No major changes needed.

We do, however, need to test this:
* I've tested linux local and remote.
* Have you tested macos? I am assuming yes from the bug report.

Windows is always a problem and we do need to check it; moving to `lstat` is a larger change that needs to be tested. I don't have access to windows.
I'd be most grateful if you (or a volunteer) tested on windows: WSL and powershell.

File: lua/nvim-tree/actions/fs/remove-file.lua (hunk 2 above)
Comment (mxple) [reply lua/nvim-tree/actions/fs/remove-file.lua:68]: I've found that making it `fs_lstat` made remove not update the tree view. Maybe a bug elsewhere?

File: lua/nvim-tree/explorer/init.lua (hunk 3 above)
Comment (mxple) [reply lua/nvim-tree/explorer/init.lua:254]: Probably a result of using `:Format`. I'll use the make style next time.

**Comment by mxple** [comment]
I am running Linux as well. I don't have access to a Windows/MacOS machine to test.

**Comment by alex-courtis** [comment]
> I am running Linux as well. I don't have access to a Windows/MacOS machine to test.

I can find someone with macos however I don't know anyone with windows.

If we can't test on windows we will need to use `if M.is_windows or M.is_wsl then` or similar to execute the original codepath on windows. They will lose the sshfs functionality but that's preferable to the risk of breaking all functionality.

**Comment by alex-courtis** [comment]
Whoops, apologies, closed by accident (ctrl-enter...)

**Comment by alex-courtis** [comment]
@mxple I do very much wish to merge this.

**Comment by mxple** [comment]
@alex-courtis I got a Windows installation up and running. I've tested `nvim-tree` on both Windows 11 and WSL. I've tested normal functionality, deleting files/folders, and symlinks. I have not tested sshfs compatibility on either Windows or WSL. 

image

**Comment by alex-courtis** [comment]
> @alex-courtis I got a Windows installation up and running. I've tested `nvim-tree` on both Windows 11 and WSL. I've tested normal functionality, deleting files/folders, and symlinks. I have not tested sshfs compatibility on either Windows or WSL.

You legend!

We now have verified base functionality on all 3.5 OS. I've done similar basic tests on macos.

We have tested sshfs compatibility on linux; that's new functionality we can be optimistic about.

**Review by alex-courtis — APPROVED** [review]
Many thanks @mxple I really appreciate all your work on this difficult one.
