### PR TITLE
fix: live filter overlay width calculation

### LINKED ISSUE #2523: Live filter window exceeds window limit with `relativenumber`
### Description

With `view.relativenumber` live filter window exceeds window width limit.

image
image

### Neovim version

```text
NVIM v0.10.0-dev-43b0e27
Build type: Release
LuaJIT 2.1.1699392533
```

### Operating system and version

Fedora

### Windows variant

_No response_

### nvim-tree version

latest master

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

vim.g.mapleader = " "

vim.keymap.set("n", "<leader>e", ":NvimTreeFocus<CR>", {noremap = true, silent = true})

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
    view = {
      relativenumber = true
    }
  }
end

-- UNCOMMENT this block for diagnostics issues, substituting pattern and cmd as appropriate.
-- Requires diagnostics.enable = true in setup.
--[[
vim.api.nvim_create_autocmd("FileType", {
  pattern = "lua",
  callback = function()
    vim.lsp.start { cmd = { "lua-language-server" } }
  end,
})
]]
```

### Steps to reproduce

1. open nvim with clean room
2. open nvim-tree(:NvimTreeFocus or `<space>e`)
3. press `f`
4. Check filter window width

### Expected behavior

_No response_

### Actual behavior

_No response_

### PR DESCRIPTION
**Pull request by geril2207**
Closes #2523

### CODE REVIEW

File: lua/nvim-tree/live-filter.lua [hunk 1]
```diff
@@ -104,25 +104,38 @@ local function configure_buffer_overlay()
   vim.api.nvim_buf_set_keymap(overlay_bufnr, "i", "<CR>", "<cmd>stopinsert<CR>", {})
 end
 
-local function create_overlay()
+local function calculate_overlay_win_width()
+  local wininfo = vim.fn.getwininfo(view.get_winnr())[1]
```
Comment (alex-courtis) [inline lua/nvim-tree/live-filter.lua:108]: `getwininfo` is hardened against nil winid.

I'm not sure how we'd get a nil however thank you for checking.

Simly returning 20 would be enough; subtracting 2 doesn't really do much.

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Many thanks for all the fantastic contributions you've made recently - quality is greatly improving!

OK:
- [ ] defaults
- [ ] view.relativenumber = true
- [ ] view.signcolumn = "no"
- [ ] view.float.enable = true

File: lua/nvim-tree/live-filter.lua (hunk 1 above)
Comment (geril2207) [reply lua/nvim-tree/live-filter.lua:109]: By doc it could be `nil`, even if  it happens we can secure by simple return 20. I don't think it reduces the readability of the code.

Comment (alex-courtis) [reply lua/nvim-tree/live-filter.lua:109]: > By doc it could be nil, maybe 1 time in 1 million and if it happens we can secure by simply return 20. I don't think it reduces the readability of the code.

Yup, that's the safest and most resilient solution.

**Review by alex-courtis — APPROVED** [review]
Many thanks for your contrubution.
