### PR TITLE
fix(#3178): handle Windows paths in ignore_dirs and add .zig-cache to defaults

### LINKED ISSUE #3178: Memory leak caused by watcher on .zig-cache/tmp files
### Description

nvim-tree.lua spawns infinite watchers when the .zig-cache/tmp folder creates a temporary file during a build process. nvim-tree.lua locks the files and prevents zig from deleting it.

I assume this a windows only issue because windows locks files when they are open.

nvim-tree.log spits out this line 1933 times per second and nvim.exe grows in memory about 10-20 megabytes per second.

```
[2025-08-07 17:54:56] [watcher] event_cb 'M:\ComputerScience\GitLocal\c-engine\.zig-cache\tmp\2c5da8ef08bfc59e' 'M:\ComputerScience\GitLocal\c-engine\.zig-cache\tmp\2c5da8ef08bfc59e'
[2025-08-07 17:54:56] [watcher] node event scheduled refresh explorer:watch:M:\ComputerScience\GitLocal\c-engine\.zig-cache\tmp\2c5da8ef08bfc59e
```

### Solution
add ```/.zig-cache``` to default ignore_dirs for watcher

https://github.com/nvim-tree/nvim-tree.lua/blob/dd2364d6802f7f57a98acb8b545ed484c6697626/lua/nvim-tree.lua#L417-L424

### Neovim version

```text
NVIM v0.11.3
Build type: Release
LuaJIT 2.1.1741730670
```

### Operating system and version

Windows 10

### Windows variant

Powershell

### nvim-tree version

nvim-tree-v1.13.0

### Clean room replication

```lua
uneccesary
```

### Steps to reproduce

1. make sure ./zig-cache is not filtered or ignored
2. nvim
3. zig build

### Expected behavior

_No response_

### Actual behavior

_No response_

### PR DESCRIPTION
**Pull request by Uanela**
This PR fixes a critical memory leak issue on Windows where `nvim-tree.lua` spawns infinite filesystem watchers when the `.zig-cache/tmp` folder creates temporary files during a build process. The watcher locks these files, preventing Zig from deleting them and causing memory to grow by 10-20 MB/second.

## Changes

1. **Added `.zig-cache` to default `ignore_dirs`** - This directory contains build artifacts not under version control, similar to existing defaults like `node_modules` and `build`.

2. **Fixed Windows path handling in `ignore_dirs`** - The forward slash prefix (e.g., `/node_modules`) used in default ignore patterns wasn't matching Windows paths (e.g., `M:\path\to\node_modules`). The fix converts forward slashes to backslashes on Windows to ensure proper pattern matching.

## Technical Details

The existing `utils.escape_special_characters` utility was not suitable for this fix as it only handles parentheses and curly braces in paths, not the fundamental path separator difference between Unix (`/`) and Windows (`\`).

The solution implements OS-specific path normalization in `is_folder_ignored()` by converting forward slashes to backslashes on Windows systems before pattern matching with `vim.fn.match()`.

## Testing

Tested on Windows 10 with Zig build process. The `.zig-cache` directory is now properly ignored, and existing defaults like `node_modules` now correctly match on Windows paths.

Closes #3178

### CODE REVIEW

File: lua/nvim-tree/explorer/watch.lua [hunk 1]
```diff
@@ -76,13 +80,15 @@ function M.create_watcher(node)
...
-      ))
+      notify.error(
+        string.format(
+          "Observed %d consecutive file system events with interval < %dms, exceeding filesystem_watchers.max_events=%s. Disabling watcher for directory '%s'. Consider adding this directory to filesystem_watchers.ignore_dirs",
+          watcher.data.outstanding_events,
+          M.config.filesystem_watchers.max_events,
+          M.config.filesystem_watchers.debounce_delay,
+          node.absolute_path
+        )
+      )
```
Comment (alex-courtis) [inline lua/nvim-tree/explorer/watch.lua]: Please do not make any formatting changes unrelated to this PR.

File: lua/nvim-tree/explorer/watch.lua [hunk 2]
```diff
@@ -44,6 +44,10 @@ local function is_folder_ignored(path)
 
   if type(M.config.filesystem_watchers.ignore_dirs) == "table" then
     for _, ignore_dir in ipairs(M.config.filesystem_watchers.ignore_dirs) do
+      if utils.is_windows or true then
+        ignore_dir = ignore_dir:gsub("/", "\\") or ignore_dir
```
Comment (alex-courtis) [inline lua/nvim-tree/explorer/watch.lua]: We will need to double escape the backslashes as per testing: https://github.com/nvim-tree/nvim-tree.lua/issues/3178#issuecomment-3862970723

**Comment by Uanela** [comment]
I've reverted the unrelated formatting (sorry for this one) and double escaped the backslashes I searched about what it would cause and makes sense thanks again for the call.

Even after reverting the formatting there still some checks that are not passing even on my local I need to commit with `--no-verify`.

File: lua/nvim-tree/explorer/watch.lua [hunk 3]
```diff
@@ -36,23 +36,28 @@ local IGNORED_PATHS = {
...
-
-  return false
+	for _, folder in ipairs(IGNORED_PATHS) do
+		if vim.startswith(path, folder) then
+			return true
+		end
+	end
+
+	if type(M.config.filesystem_watchers.ignore_dirs) == "table" then
+		print(vim.inspect(M.config.filesystem_watchers.ignore_dirs))
```
Comment (alex-courtis) [inline lua/nvim-tree/explorer/watch.lua]: Please remove the print...

**Review by alex-courtis — CHANGES_REQUESTED** [review]
> I've reverted the unrelated formatting (sorry for this one) and double escaped the backslashes I searched about what it would cause and makes sense thanks again for the call.
> 
> Even after reverting the formatting there still some checks that are not passing even on my local I need to commit with `--no-verify`.

I see. It looks like `is_folder_ignored` is indented with tabs, not spaces. You can format just that file with `:lua vim.lsp.buf.format()` or `gg=G`

You have identified a bigger problem: `style-check` does not identify all the issue that `style-fix` does. Issue incoming... #3271

Please:

- [ ] format `watch.lua`
- [ ] remove the print statement

**Comment by Uanela** [comment]
All good to go Sir Alex

File: doc/nvim-tree-lua.txt [hunk 4]
```diff
@@ -2188,6 +2188,7 @@ Following is the default configuration, see |nvim_tree.config| for details. >lua
           "/build",
           "/node_modules",
           "/target",
+          "/.zig-cache",
```
Comment (alex-courtis) [inline doc/nvim-tree-lua.txt:2191]: This is not present in `nvim-tree.lua` `DEFAULT_OPTS`

Please add it and re-generate the help: https://github.com/nvim-tree/nvim-tree.lua/blob/master/CONTRIBUTING.md#help-documentation

File: lua/nvim-tree/explorer/watch.lua [hunk 5]
```diff
@@ -44,6 +44,10 @@ local function is_folder_ignored(path)
 
   if type(M.config.filesystem_watchers.ignore_dirs) == "table" then
     for _, ignore_dir in ipairs(M.config.filesystem_watchers.ignore_dirs) do
+      if utils.is_windows or true then
```
Comment (alex-courtis) [inline lua/nvim-tree/explorer/watch.lua]: Should that `true` be there?

Testing shows a regression:

```sh
mkdir foo
mkdir .ccls-cache
```

Set `filters.dotfiles` and `git_ignored` false
Open tree and directories

```sh
touch foo/1
```

Expected: 1 appears immediately.

```sh
touch .ccls-cache/2
```
Expected: 2 does not appear until R
Actual: appears immediately

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Getting close...

Please:

- [x] Add zig-cache to defaults https://github.com/nvim-tree/nvim-tree.lua/pull/3261/changes#r2819702785
- [x] Resolve regression https://github.com/nvim-tree/nvim-tree.lua/pull/3261/changes#r2819704632

File: lua/nvim-tree/explorer/watch.lua (hunk 5 above)
Comment (Uanela) [reply lua/nvim-tree/explorer/watch.lua]: This was a testing I was doing my bad, I should have removed it

**Comment by Uanela** [comment]
@alex-courtis I've opened 3 PR so far and some issues, where 2 PR's refactors and one bug fix (very simple and with clear hints).

How would you rate my contributions from 0-10 so far, only rate if possible, maybe you lack some data I don't know.

**Comment by alex-courtis** [comment]
Tested OK:

```sh
mkdir foo
mkdir .ccls-cache
mkdir .zig-cache
```

Set `filters.dotfiles` and `git_ignored` false
Open tree and directories

```sh
touch foo/1
```

Expected: 1 appears immediately.

```sh
touch .ccls-cache/2
```
Expected: 2 does not appear until R


```sh
touch .zig-cache/3
```
Expected: 3 does not appear until R

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Tested OK: https://github.com/nvim-tree/nvim-tree.lua/pull/3261#issuecomment-3924332677 on linux and you have tested windows.

Please accept my deepest apologies, I missed this one: we need to update the defaults in `lua/nvim-tree/_meta/config/filesystem_watchers.lua` and generate help.

How do you like to handle these tiny nits?
1. Fix it yourself
2. I push a fix
No drama either way, everyone has their preference.

**Comment by Uanela** [comment]
Done.

**Review by alex-courtis — APPROVED** [review]
Love your work @Uanela 

Edit: apologies, approved too early.

We're getting a CI fail on the help txt for the new default: https://github.com/nvim-tree/nvim-tree.lua/actions/runs/22170271960/job/64106472696?pr=3261

Please:

- [ ] Regenerate help to include the recent change https://github.com/nvim-tree/nvim-tree.lua/blob/master/CONTRIBUTING.md#help-documentation

**Comment by Uanela** [comment]
Docs regeneration done.

I got the problem that wasn't allowing me to regenerate the docs:

```bash
/tmp/src/neovim-stable/src/gen/gen_vimdoc.lua.org -> /tmp/src/neovim-stable/src/gen/gen_vimdoc.lua
scripts/help-defaults.sh
sed: -e: No such file or directory
make: *** [help-update] Error 1
uanela_como@Uanelas-MacBook-Pro nvim-tree.lua % sudo make help-update
```

the `sed` command on macos is `gsed` for (GNU sed) so I need to export `gsed` to `sed` in order to be able to update the docs.

**Comment by alex-courtis** [comment]
> Docs regeneration done.
> 
> I got the problem that wasn't allowing me to regenerate the docs:
> 
> ```shell
> /tmp/src/neovim-stable/src/gen/gen_vimdoc.lua.org -> /tmp/src/neovim-stable/src/gen/gen_vimdoc.lua
> scripts/help-defaults.sh
> sed: -e: No such file or directory
> make: *** [help-update] Error 1
> uanela_como@Uanelas-MacBook-Pro nvim-tree.lua % sudo make help-update
> ```
> 
> the `sed` command on macos is `gsed` for (GNU sed) so I need to export `gsed` to `sed` in order to be able to update the docs.

Great catch! Lazy of me: I used `sed -e` instead of the macos/bsd compatible `sed -E`

Edit: raised #3275
