### PR TITLE
fix(#2516): diagnostics icon highlight group matches the documentation: NvimTreeLspDiagnosticsInfo -> Information

### LINKED ISSUE #2516: Diagnostics Info icon highlight group is incorrect: Expected "NvimTreeLspDiagnosticsInfo" but found "NvimTreeLspDiagnosticsInformation"
### Description

The diagnostics highlight group used for `info` icon is incorrect. NvimTree has set following highlight groups:
```
NvimTreeLspDiagnosticsWarningFolderText xxx links to NvimTreeLspDiagnosticsWarningText
NvimTreeLspDiagnosticsWarningText xxx links to NvimTreeLspDiagnosticsWarning
NvimTreeLspDiagnosticsErrorFolderText xxx links to NvimTreeLspDiagnosticsErrorText
NvimTreeLspDiagnosticsErrorText xxx links to NvimTreeLspDiagnosticsError
NvimTreeLspDiagnosticsInformation xxx links to DiagnosticInfo
...
NvimTreeLspDiagnosticsWarning xxx links to DiagnosticWarn
NvimTreeLspDiagnosticsError xxx links to DiagnosticError
NvimTreeLspDiagnosticsHint xxx links to DiagnosticHint
```
However the highlight group wanted for the `info` icon is `NvimTreeLspDiagnosticsInfo` as defined here: https://github.com/nvim-tree/nvim-tree.lua/blob/c763861afb32f839555f9e797f4392f54ef4ad23/lua/nvim-tree/renderer/components/diagnostics.lua#L73-L76.

I assume the highlight group should be renamed to `*Information` or the NvimTree highlight groups should be corrected with `*Info`

### Neovim version

```text
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1694285958
```

### Operating system and version

Linux 6.1.55-1-MANJARO

### Windows variant

_No response_

### nvim-tree version

master

### Clean room replication

```lua
require("nvim-tree").setup({
	reload_on_bufenter = true,
	select_prompts = true,
	hijack_netrw = false,
	view = {
		width = 50,
	},
	renderer = {
		root_folder_label = ":~:s?$?/?",
		special_files = {},
		highlight_git = true,
		highlight_diagnostics = true,
		highlight_modified = "all",
		indent_markers = {
			enable = true,
		},
		icons = {
			show = {
				folder_arrow = true,
			},
		},
	},
	modified = {
		enable = true,
		show_on_dirs = true,
		show_on_open_dirs = true,
	},
	hijack_directories = {
		enable = false,
		auto_open = true,
	},
	update_focused_file = {
		enable = true,
	},
	diagnostics = {
		enable = true,
		show_on_dirs = true,
		show_on_open_dirs = true,
		debounce_delay = 50,
		icons = {
			hint = "",
			info = "",
			warning = "",
			error = "",
		},
	},
	filters = {
		git_ignored = true,
		dotfiles = true,
		git_clean = false,
		no_buffer = false,
		custom = {},
		exclude = {
			"node_modules",
		},
	},
	actions = {
		expand_all = {
			exclude = {
				"node_modules",
				"target",
				"build",
				".git",
			},
		},
	},
	tab = {
		sync = {
			open = true,
			close = true,
			ignore = {},
		},
	},
})
```

### Steps to reproduce

1. Open nvim with diagnostic enabled workspace (literally any project will do)
2. Open nvim-tree and a file that has info level diagnostics available
3. See results on the nvim-tree the icon color is not highlighted correctly but remains grey color.

### Expected behavior

Should highlight color the icon according to used color theme:
image

### Actual behavior

But the color remains grey:
image

### PR DESCRIPTION
**Pull request by alex-courtis**
fixes #2516 

Proper overhaul incoming: #2415

### CODE REVIEW

**Comment by alex-courtis** [comment]
Tested OK https://github.com/nvim-tree/nvim-tree.lua/issues/2516#issuecomment-1797014920

File: lua/nvim-tree/renderer/components/diagnostics.lua [hunk 1]
```diff
@@ -72,7 +72,7 @@ function M.setup(opts)
   }
   M.ICON[vim.diagnostic.severity.INFO] = {
     str = M.config.diagnostics.icons.info,
-    hl = { "NvimTreeLspDiagnosticsInfo" },
+    hl = { "NvimTreeLspDiagnosticsInformation" },
```
Comment (Akmadan23) [inline lua/nvim-tree/renderer/components/diagnostics.lua:75]: It's a minor gripe, but I would do it the other way around, replacing the others *Information with *Info, since the level is `info` it would be more intuitive

Comment (alex-courtis) [reply lua/nvim-tree/renderer/components/diagnostics.lua:75]: Agreed. `Info` is the consistent option.

I'm just putting this quick fix in for now. I've updated them all to `Info` in the long running feature branch: https://github.com/nvim-tree/nvim-tree.lua/pull/2455/files#diff-b5b2d1abcb86ead5a2319f7e065a7545b834a407cc9f420590d7acebb285fca9R2283
