### PR TITLE
fix(#1731 #1723 #1716): handle all external file system changes

### LINKED ISSUE #1723: find_file For New File Leaves Node In Inconsistent State
### Description

find_file for a valid file that is not known in a closed directory results in the closed directory unable to be opened.

### Neovim version

```text
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.0.6-arch1-1

### nvim-tree version

a0f3e99

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
    filesystem_watchers = {
      enable = false,
    },
    log = {
      enable = true,
      truncate = true,
      types = {
        all = false,
        config = false,
        copy_paste = false,
        dev = true,
        diagnostics = false,
        git = true,
        profile = false,
        watcher = true,
      },
    },
  }
end
```

### Steps to reproduce

`mkdir x`
`touch x/a`
`:NvimTreeOpen`
open x
close x
`!touch x/b`
`:lua require("nvim-tree.api").tree.find_file("x/b")`

### Expected behavior

Node x requires two `edit` to open.

### Actual behavior

Open with one `edit`.

### LINKED ISSUE #1731: Externally Created File Not Always Visible
### Description

Creating a new file externally to vim does not always result in it being visible.

### Neovim version

```text
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.0.6-arch1-1

### nvim-tree version

a0f3e99

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

```
mkdir x
touch x/a
ln -s x a
ln -s x z
```
open each folder and close them
```
:!touch x/b
```
open each folder

### Expected behavior

b visible in all folders

### Actual behavior

b visible only in a

### PR DESCRIPTION
**Pull request by alex-courtis**
resolves #1731 #1723 #1716

Link directory nodes are the main issue here.

- watchers refresh all folders (including links) when contents are externally modified
- refresh profiling on absolute path
- find-file locks and profiles on absolute path
- find-file reloads path of the target file
- create-file invokes find-file

Outstanding, follow up PR:
- consolidate similar functions reloaders.lua and reload.lua

### CODE REVIEW

**Comment by alex-courtis** [comment]
I would be very grateful for a review and real world test over a few days.

This one has been tricky...

**Review by gegoune — APPROVED** [review]
Will use locally. Anything in particular to look out for?

**Comment by alex-courtis** [comment]
> Will use locally. Anything in particular to look out for?

Thank you.

Watchers on: find file not finding at all or selecting wrong node.

Create file is still broken for some cases.

File: lua/nvim-tree/explorer/watch.lua [hunk 1]
```diff
@@ -46,39 +32,39 @@ local function is_folder_ignored(path)
...
-    log.line("watcher", "node event scheduled %s", watcher.context)
+    log.line("watcher", "node event scheduled refresh %s", watcher.context)
     utils.debounce(watcher.context, M.debounce_delay, function()
-      M.refresh_path(watcher._path)
+      if node.link_to then
+        log.line("watcher", "node event executing refresh '%s' -> '%s'", node.link_to, node.absolute_path)
+      else
+        log.line("watcher", "node event executing refresh '%s'", node.absolute_path)
+      end
+      require("nvim-tree.explorer.reload").refresh_node(node)
```
Comment (alex-courtis) [inline lua/nvim-tree/explorer/watch.lua:59]: This will still result in one refresh for each instance of the symlinked dir, however optimising that away requires significant complexity.

**Comment by alex-courtis** [comment]
Pulling the trigger. Thanks for testing @gegoune 

This has been a difficult fix. If there are issues I plan to push forward with fixes rather than reverting again.
