### PR TITLE
fix(#1716): focus file/directory when created in a sub-directory, don't dispatch FolderCreated on file creation

### LINKED ISSUE #1716: Cursor does not focus on file created when creating file with nested directory
### Description

Cursor does not focus on file created when creating file with nested directory

### Neovim version

```text
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux-5.19.12

### nvim-tree version

6ca6f99e7689c68679e8f0a58b421545ff52931f

### Minimal config

```lua
require("nvim-tree").setup({
  update_focused_file = {
    enable = true
  },
  git = {
    ignore = false
  },
  actions = {
    open_file = {
      quit_on_open = true
    }
  },
  view = {
    width = 200,
    number = true,
    relativenumber = true,
    side = 'left',
    mappings = {
      list = {
        { key = "-", cb = tree_cb("close") },
        { key = { "<BS>", "<C-o>" }, action = "close_node" },
      }
    }
  }
})
```

### Steps to reproduce

1. nvim
2. a
3. somefolder/anotherfolder/a.c
4. cursor focuses on the top of the tree

### Expected behavior

Cursor should focus on the top of the tree

image

### Actual behavior

Cursor should focus on the file created

image

### PR DESCRIPTION
**Pull request by alex-courtis**
fixes #1716 

Synchronous refresh is always performed on creation. Node is found following create/refresh.

### CODE REVIEW

File: lua/nvim-tree/actions/fs/create-file.lua [hunk 1]
```diff
@@ -101,22 +100,14 @@ function M.fn(node)
           is_error = true
           break
         end
+        events._dispatch_folder_created(path_to_create)
```
Comment (alex-courtis) [inline lua/nvim-tree/actions/fs/create-file.lua:103]: unrelated bug

**Comment by alex-courtis** [comment]
Not working for the case of a closed node that was previously opened.

**Comment by alex-courtis** [comment]
Tested OK: https://github.com/nvim-tree/nvim-tree.lua/issues/1716#issuecomment-1304428085
