### PR TITLE
Make create/paste add files to closed folders

### LINKED ISSUE #1800: `create_in_closed_folder` doesn't apply to paste
### Description

When the `create_in_closed_folder` option is set, creating a file with a directory highlighted creates the file in the directory that's highlighted. When pasting a file, it does not.

Not to sound disrespectful, but I'm a little unclear as to why this option is needed at all... Is this just precedent from NerdTree? It's unusual behavior for graphical file trees anywhere else for the opened state of a selected directory to impact paste. I can't imagine I'm the first to notice, but there were no other issues...

### Neovim version

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Operating System: Arch Linux Linux 5.15.78-1-lts

### nvim-tree version

829e9f6

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

Create a directory like:
```
.
├── bar
│   └── baz
└── foo.xyz
```
1. select `bar`
2. press `<CR>`
3. select `foo.xyz`
4. press `x`
5. select `bar/baz`
6. press `p`

### Expected behavior

File becomes `/bar/baz/foo.xyz`

### Actual behavior

File becomes `/bar/foo.xyz`

### PR DESCRIPTION
**Pull request by ehaynes99**
Fixes #1800 
By default, creating or pasting a file with a closed directory selected in the tree should add the file inside of the directory. Alternately, to have them be created in the parent directory, the option `create_in_close_folder` can be set to `false`.

### CODE REVIEW

**Comment by alex-courtis** [comment]
Approved pending disucussion: https://github.com/nvim-tree/nvim-tree.lua/issues/1800#issuecomment-1336303663

**Comment by alex-courtis** [comment]
It seems we have reached consensus.

@ehaynes99 are you happy to remove `create_in_closed_folder` and apply sane defaults?

We got lucky with removal. We can add to legacy.lua:
```lua
local function removed(opts)
---
  if opts.create_in_closed_folder then
    notify.warn "create_in_closed_folder has been removed. Please use api.fs.create to add a file under your desired node."
  end
  opts.create_in_closed_folder = nil
end
```

**Comment by ehaynes99** [comment]
Ok, updated. Please take a look.

File: lua/nvim-tree/legacy.lua [hunk 1]
```diff
@@ -268,12 +268,6 @@ local g_migrations = {
       o.respect_buf_cwd = vim.g.nvim_tree_respect_buf_cwd == 1
     end
   end,
-
-  nvim_tree_create_in_closed_folder = function(o)
```
Comment (alex-courtis) [inline lua/nvim-tree/legacy.lua:272]: I think it's time to remove the `g:` legacy. Maybe after merging this...

**Review by alex-courtis — APPROVED** [review]
Tested OK:
* paste
* create

Many thanks for your contribution and driving this better behaviour.

File: lua/nvim-tree/legacy.lua (hunk 1 above)
Comment (gegoune) [reply lua/nvim-tree/legacy.lua:272]: I am fine with that - it's been long enough.

Comment (alex-courtis) [reply lua/nvim-tree/legacy.lua:272]: Fantastic!
