### PR TITLE
fix(#1626): obey splitright/below when splitting existing windows

### LINKED ISSUE #1626: vsplit always opens to the left, can it be on the right?
### Description

When I'm over a file in nvim-tree and press <C-v> to open it in a vsplit, I want the file to open the right of the current file I have open. But it always is placed to the left of the current file. I'm sure this is a config setting I'm missing.

### Neovim version

```text
NVIM v0.9.0-dev-5-g9353e2f7e
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by root@FM-WYN2K2JQ9D
```

### Operating system and version

macOS 12.4

### nvim-tree version

7282f7d

### Minimal config

```lua
vim.opt.splitbelow = true
vim.opt.splitright = true

local tree_cb = require 'nvim-tree.config'.nvim_tree_callback
require('nvim-tree').setup({
    actions             = {
        open_file = { quit_on_open = true },
    },
    renderer            = {
        indent_markers = { enable = true }
    },
    respect_buf_cwd     = true,
    update_cwd          = true,
    update_focused_file = { enable = true, update_cwd = true },
    view                = {
        adaptive_size = true,
        mappings = {
            custom_only = false,
            list = {
                { key = "<CR>", cb = tree_cb("edit") },
                { key = "h", cb = tree_cb("close_node") },
                { key = "l", cb = tree_cb("open_node") },
                { key = "<BS>", cb = tree_cb("dir_up") },
                { key = "?", cb = tree_cb("toggle_help") },
                { key = "<C-e>", cb = tree_cb("close") },
                { key = "<C-s>", cb = tree_cb("split") },
            }
        },
        width = 35,
        side = 'right',
    },
})
```

### Steps to reproduce

1. have a file open in vim buffer `current_file`
2.  `:NvimTreeOpen`
3. navigate to file
4. `<C-v>` to open in vsplit

### Expected behavior

File opens to the right of `current_file`

### Actual behavior

File opens to the left of `current_file`

### PR DESCRIPTION
**Pull request by alex-courtis**
fixes #1626

splitright and splitbelow were not being obeyed when splitting a non-nvim-tree window.

### CODE REVIEW

File: lua/nvim-tree/actions/node/open-file.lua [hunk 1]
```diff
@@ -179,32 +179,34 @@ local function open_in_new_window(filename, mode, win_ids)
   if not target_winid then
     return
   end
-  local do_split = mode == "split" or mode == "vsplit"
-  local split_side = (view.View.side == "right") and "aboveleft" or "belowright"
+
+  local create_new_window = #api.nvim_list_wins() == 1
+  local new_window_side = (view.View.side == "right") and "aboveleft" or "belowright"
```
Comment (alex-courtis) [inline lua/nvim-tree/actions/node/open-file.lua:184]: I resisted further refactoring.

**Comment by alex-courtis** [comment]
Test cases:

Each of

- [x] defaults
- [x] defaults: splitright and splitbelow
- [x] right
- [x] right: splitright and splitbelow

Tested with

- [x] edit
- [x] `<C-v>`
- [x] `<C-x>`
- [x] nohidden open
- [x] open_on_setup start in dir, retesting #1553
- [x] window on different tab

**Review by kyazdani42 — APPROVED** [review]
