### PR TITLE
fix(#2954): more efficient LSP updates, increase diagnostics.debounce_delay from 50ms to 500ms

### LINKED ISSUE #2954: LSP diagnostics inside nvim-tree may flicker
### Description

When `diagnostics.enable = true` and a filetype-generic LSP (e.g. `typos-lsp`) is running, one may see flickering of diagnostics in the nvim-tree buffer/window.

On a more complex neovim setup than "Clean room replication" I also observed moderate to high CPU load.

A possible workaround for me was to add a check for `vim.bo[bufnr].buflisted` in `view.lua:491:is_buf_valid`. I am new to this stuff and not sure if this would be a valid solution.

### Neovim version

```text
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1727870382
```

### Operating system and version

Linux 6.11.3

### Windows variant

-

### nvim-tree version

master

### Clean room replication

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvt-min/site]])
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			"nvim-tree/nvim-tree.lua",
			"nvim-tree/nvim-web-devicons",
			-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing nvim-tree and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]])
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
	require("nvim-tree").setup({
		diagnostics = {
			enable = true,
		},
	})
	require("nvim-tree.api").tree.open()
end

-- UNCOMMENT this block for diagnostics issues, substituting pattern and cmd as appropriate.
-- Requires diagnostics.enable = true in setup.

vim.api.nvim_create_autocmd("FileType", {
	pattern = "*",
	callback = function()
                -- please adjust path to `typos-lsp`
		vim.lsp.start({ cmd = { "/home/des-b/.local/share/nvim/mason/bin/typos-lsp" } })
	end,
})
```

### Steps to reproduce

1. Put a file with an invalid name: `som.txt`
2. Run neovim

### Expected behavior

Diagnostic on `som.txt` shown in nvim-tree should just show ''typos: `som` should be `some`"

### Actual behavior

The diagnostic is shown but flickers every few ~100ms

### PR DESCRIPTION
**Pull request by alex-courtis**
fixes #2954 

@des-b I'd be most grateful for your review and thoughts.

This changes the approach to LSP:
* examine the `DiagnosticChanged` data on the event (sync) thread
* `NODE_SEVERITIES` and `NODE_SEVERITIES_VERSION` only updated on delta
* on delta a redraw is scheduled

The debounce delay was increased as there are a _lot_ of events as the user types.

It's not clear whether a full redraw `R` is needed; it could clear `NODE_SEVERITIES` and rebuild it. YAGNI?

### CODE REVIEW

File: lua/nvim-tree/diagnostics.lua [hunk 1]
```diff
@@ -135,35 +108,77 @@ local function from_cache(node)
     for bufname, severity in pairs(NODE_SEVERITIES) do
       local node_contains_buf = vim.startswith(bufname, nodepath .. "/")
       if node_contains_buf then
-        if severity == M.severity.max then
+        if not max_severity or severity < max_severity then
```
Comment (alex-courtis) [inline lua/nvim-tree/diagnostics.lua:111]: This became a warning hence it was simplified.

File: lua/nvim-tree/diagnostics.lua [hunk 2]
```diff
@@ -17,7 +17,7 @@ local COC_SEVERITY_LEVELS = {
 }
 
 ---Absolute Node path to LSP severity level
----@alias NodeSeverities table<string, lsp.DiagnosticSeverity>
+---@alias NodeSeverities table<string, vim.diagnostic.Severity>
```
Comment (alex-courtis) [inline lua/nvim-tree/diagnostics.lua:20]: `lsp.DiagnosticSeverity` and `vim.diagnostic.Severity` are effectively the same. It's not clear which is preferred, so I went with the one from `vim.Diagnostic`
