### PR TITLE
fix(#2945): stack overflow on api.git.reload or fugitive event with watchers disabled

### LINKED ISSUE #2945: reload_git and reload_node_status stack overflow
### Description

If i run Git! pull which is a command available through vim fugitive, then i get this error

image

`Error detected while processing function 26_RunClose[23]..26_RunFinished[12]..fugitive#DidChange[9]..26_DoAutocmdChanged[17]..function 26_RunClose[23]..26_RunFinished[12]..fugitive#DidChange[9]..26_DoAutocmdChanged[10]..User Autocommands for "FugitiveChanged":
Error executing lua callback: stack overflow
stack traceback:
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:145: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
...hare/nvim/lazy/nvim-tree.lua/lua/nvim-tree/node/init.lua:150: in function 'reload_node_status'
.../nvim/lazy/nvim-tree.lua/lua/nvim-tree/explorer/init.lua:371: in function 'reload_git'
...a/.local/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree.lua:255: in function <...a/.local/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree.lua:251>`

If i point nvim-tree to commit = "517e4fbb9ef3c0986da7047f44b4b91a2400f93c" it does not break

I think the issue is related to this https://github.com/nvim-tree/nvim-tree.lua/issues/2930

### Neovim version

```text
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1724512491
Run "nvim -V1 -v" for more info
```

### Operating system and version

macOs

### Windows variant

_No response_

### nvim-tree version

main

### Clean room replication

```lua
**
```

### Steps to reproduce

Git! pull

### Expected behavior

Reload properly

### Actual behavior

Error

### PR DESCRIPTION
**Pull request by alex-courtis**
fixes #2945 

reapplies #2916

### CODE REVIEW

File: lua/nvim-tree/node/init.lua [hunk 1]
```diff
@@ -0,0 +1,347 @@
...
+end
+
+---@param projects table
+function BaseNode:reload_node_status(projects)
+  local toplevel = git.get_toplevel(self.absolute_path)
+  local status = projects[toplevel] or {}
+  for _, node in ipairs(self.nodes) do
+    node:update_git_status(self:is_git_ignored(), status)
+    if node.nodes and #node.nodes > 0 then
+      node:reload_node_status(projects)
```
Comment (alex-courtis) [inline lua/nvim-tree/node/init.lua:150]: Was previously `self:reload_node_status(projects)` resulting in infinite recursion.
