### PR TITLE
fix(#1976): improve `$GIT_DIR` handling

### LINKED ISSUE #1976: File system watcher throws error when opening git repo with $GIT_DIR set
### Description

When opening nvim in a git repo with `$GIT_DIR` set to something other than `.git` nvim-tree throws the error `[NvimTree] "Could not start the fs_event watcher for path <path_to_repo>/.git : ENOENT"`

### Neovim version

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.1.9-arch1-1

### nvim-tree version

02fdc26

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "nvim-tree/nvim-tree.lua",
      "nvim-tree/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

1. Make a git repo with `GIT_DIR=test git init`
2. Open nvim with `GIT_DIR=test GIT_WORK_TREE=. nvim`
3. Open NvimTree

### Expected behavior

_No response_

### Actual behavior

_No response_

### PR DESCRIPTION
**Pull request by dmehala**
- Retrieve $GIT_DIR using `git rev-parse --absolute-git-dir`
- Move $GIT_DIR ignore in the project exploration part

Resolves #1976

### CODE REVIEW

File: lua/nvim-tree/git/utils.lua [hunk 1]
```diff
@@ -3,6 +3,22 @@ local log = require "nvim-tree.log"
 
 local has_cygpath = vim.fn.executable "cygpath" == 1
 
+local function norm_path(path)
+  -- git always returns path with forward slashes
+  if vim.fn.has "win32" == 1 then
```
Comment (alex-courtis) [inline lua/nvim-tree/git/utils.lua:8]: Windows... is always a problem. I cannot verify it however you will be testing it.

Please add `utils.lua` `is_msys2`

However... before you do that... I suspect the same problem may be exhibited on cygwin and WSL. Please test those two as well and maybe do this for `is_windows`

File: lua/nvim-tree/git/init.lua [hunk 2]
```diff
@@ -143,29 +143,36 @@ function M.load_project_status(cwd)
     timeout = M.config.git.timeout,
   }
 
+  local git_directory = git_utils.get_git_directory(project_root)
```
Comment (alex-courtis) [inline lua/nvim-tree/git/init.lua:146]: This is good, it's done only once.

File: lua/nvim-tree/git/utils.lua [hunk 3]
```diff
@@ -3,6 +3,22 @@ local log = require "nvim-tree.log"
 
 local has_cygpath = vim.fn.executable "cygpath" == 1
 
+local function norm_path(path)
```
Comment (alex-courtis) [inline lua/nvim-tree/git/utils.lua:6]: There should be a method in `utils.lua` to do this. If not, please add one.

**Comment by alex-courtis** [comment]
Testing with a default `.git` setup had issues around identifying the `.git` directory. Follwing any git status it appears to be treated as a normal directory, with watchers etc. created.

# setup
mkdir default
cd default
git init
touch x
git add x
git commit -m "initial commit"


# master
open tree
.git is shown
touch x
```
[2023-02-20 11:04:32] [watcher] event_cb '/home/alex/1976/default' 'x'
[2023-02-20 11:04:32] [watcher] node event scheduled refresh explorer:watch:/home/alex/1976/default:1
[2023-02-20 11:04:32] [watcher] node event executing refresh '/home/alex/1976/default'
[2023-02-20 11:04:32] [git] running job with timeout 400ms
[2023-02-20 11:04:32] [git] git --no-optional-locks status --porcelain=v1 -z --ignored=matching -u /home/alex/1976/default
[2023-02-20 11:04:32] [git] job success    /home/alex/1976/default /home/alex/1976/default
```
touch .git/config
```
[2023-02-20 11:04:52] [watcher] event_cb '/home/alex/1976/default/.git' 'config'
[2023-02-20 11:04:52] [watcher] git event scheduled '/home/alex/1976/default'
[2023-02-20 11:04:52] [watcher] git event executing '/home/alex/1976/default'
[2023-02-20 11:04:52] [git] running job with timeout 400ms
[2023-02-20 11:04:52] [git] git --no-optional-locks status --porcelain=v1 -z --ignored=matching -u
[2023-02-20 11:04:52] [git] job success    /home/alex/1976/default nil
```


# branch
open tree
.git is not shown
touch x
```
[2023-02-20 11:05:29] [watcher] event_cb '/home/alex/1976/default' 'x'
[2023-02-20 11:05:29] [watcher] node event scheduled refresh explorer:watch:/home/alex/1976/default:1
[2023-02-20 11:05:29] [watcher] node event executing refresh '/home/alex/1976/default'
[2023-02-20 11:05:29] [git] running job with timeout 400ms
[2023-02-20 11:05:29] [git] git --no-optional-locks status --porcelain=v1 -z --ignored=matching -u /home/alex/1976/default
[2023-02-20 11:05:29] [git] job success    /home/alex/1976/default /home/alex/1976/default
[2023-02-20 11:05:29] [watcher] Watcher:new '/home/alex/1976/default/.git' nil
```
.git is now shown
touch .git/config
```
[2023-02-20 11:06:00] [watcher] event_cb '/home/alex/1976/default/.git' 'config'
[2023-02-20 11:06:00] [watcher] git event scheduled '/home/alex/1976/default'
[2023-02-20 11:06:00] [watcher] node event scheduled refresh explorer:watch:/home/alex/1976/default/.git:4
[2023-02-20 11:06:00] [watcher] git event executing '/home/alex/1976/default'
[2023-02-20 11:06:00] [git] running job with timeout 400ms
[2023-02-20 11:06:00] [git] git --no-optional-locks status --porcelain=v1 -z --ignored=matching -u
[2023-02-20 11:06:00] [watcher] node event executing refresh '/home/alex/1976/default/.git'
[2023-02-20 11:06:00] [git] { "git", "-C", "/home/alex/1976/default/.git", "rev-parse", "--show-toplevel" }
fatal: this operation must be run in a work tree
[2023-02-20 11:06:00] [watcher] Watcher:new '/home/alex/1976/default/.git/branches' nil
[2023-02-20 11:06:00] [watcher] Event:new '/home/alex/1976/default/.git/branches'
[2023-02-20 11:06:00] [watcher] Event:start '/home/alex/1976/default/.git/branches'
[2023-02-20 11:06:00] [watcher] Watcher:new '/home/alex/1976/default/.git/hooks' nil
[2023-02-20 11:06:00] [watcher] Event:new '/home/alex/1976/default/.git/hooks'
[2023-02-20 11:06:00] [watcher] Event:start '/home/alex/1976/default/.git/hooks'
[2023-02-20 11:06:00] [watcher] Watcher:new '/home/alex/1976/default/.git/info' nil
[2023-02-20 11:06:00] [watcher] Event:new '/home/alex/1976/default/.git/info'
[2023-02-20 11:06:00] [watcher] Event:start '/home/alex/1976/default/.git/info'
[2023-02-20 11:06:00] [watcher] Watcher:new '/home/alex/1976/default/.git/logs' nil
[2023-02-20 11:06:00] [watcher] Event:new '/home/alex/1976/default/.git/logs'
[2023-02-20 11:06:00] [watcher] Event:start '/home/alex/1976/default/.git/logs'
[2023-02-20 11:06:00] [watcher] Watcher:new '/home/alex/1976/default/.git/objects' nil
[2023-02-20 11:06:00] [watcher] Event:new '/home/alex/1976/default/.git/objects'
[2023-02-20 11:06:00] [watcher] Event:start '/home/alex/1976/default/.git/objects'
[2023-02-20 11:06:00] [watcher] Watcher:new '/home/alex/1976/default/.git/refs' nil
[2023-02-20 11:06:00] [watcher] Event:new '/home/alex/1976/default/.git/refs'
[2023-02-20 11:06:00] [watcher] Event:start '/home/alex/1976/default/.git/refs'
[2023-02-20 11:06:00] [git] job success    /home/alex/1976/default nil
```

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Looking good so far.

Initial testing shows things are mostly working for a default `.git` directory and a user specified one.

Please:

- [ ] test cygwin / WSL
- [ ] use a norm_path from utils.lua
- [ ] deal with https://github.com/nvim-tree/nvim-tree.lua/pull/2012#issuecomment-1436143786

**Comment by dmehala** [comment]
Thanks for your feedback @alex-courtis. I hope I will have time today or tomorrow to improve the PR.

**Comment by dmehala** [comment]
I think I've fixed #2012 comment. However, I was not able to test on cygwin and WSL, to be honest, I just reused [code already written](https://github.com/nvim-tree/nvim-tree.lua/blob/1b453441f4b1a501a6251db4138cf67172d0d5d2/lua/nvim-tree/git/utils.lua#L21-L31).

**Comment by alex-courtis** [comment]
> I think I've fixed #2012 comment. However, I was not able to test on cygwin and WSL, to be honest, I just reused [code already written](https://github.com/nvim-tree/nvim-tree.lua/blob/1b453441f4b1a501a6251db4138cf67172d0d5d2/lua/nvim-tree/git/utils.lua#L21-L31).

Ah, damn. I assumed you were using windows.

Do you have a windows environment you can test with?

File: lua/nvim-tree/utils.lua [hunk 4]
```diff
@@ -42,6 +44,21 @@ function M.path_split(path)
   return path:gmatch("[^" .. path_separator .. "]+" .. path_separator .. "?")
 end
 
+function M.norm_path(path)
+  if M.is_windows then
```
Comment (alex-courtis) [inline lua/nvim-tree/utils.lua:48]: I left a comment in utils.lua `-- false for WSL` however this (unchanged) code indicates that comment is incorrect.

We're not changing anything so I'll remove it.

**Review by alex-courtis — CHANGES_REQUESTED** [review]
This appears to work for default and different git dirs. I'll fully test once we sort out the watcher ignores.

Please:

- [ ] move https://github.com/nvim-tree/nvim-tree.lua/pull/2012/files#r1125590684
- [x] resolve https://github.com/nvim-tree/nvim-tree.lua/pull/2012#discussion_r1125587433

File: lua/nvim-tree/git/init.lua (hunk 2 above)
Comment (alex-courtis) [reply lua/nvim-tree/git/init.lua:146]: This should be moved inside `if M.config.filesystem_watchers.enable then` so that we don't unnecessarily execute this when watchers are disabled.

File: lua/nvim-tree/git/init.lua [hunk 5]
```diff
@@ -143,23 +143,33 @@ function M.load_project_status(cwd)
...
+          reload_tree_at(w.project_root)
+        end)
+      end
 
-    watcher = Watcher:new(utils.path_join { project_root, ".git" }, WATCHED_FILES, callback, {
-      project_root = project_root,
-    })
+      -- Add $GIT_DIR to the list of directory to ignore
+      local base_gitdir = utils.path_basename(git_directory)
+      table.insert(M.config.filesystem_watchers.ignore_dirs, base_gitdir)
```
[the remark this answers is not in the document]
Comment (dmehala) [reply lua/nvim-tree/git/init.lua:167]: > This is, however, a hack, not a solution.

I agree.

IMHO, the issue boils down to `create_watcher` being responsible to know what can be watched or not. I would argue it's the caller's responsibility.

## Proposal

- add `watch.disable_watcher(path)`
   - Adds to a new list `M.ignored_paths` which is initialized with `IGNORED_PATHS`
- update `create_watcher` to not check if the node is ignored. ([remove this part](https://github.com/nvim-tree/nvim-tree.lua/blob/5860ac3950252384af440847fc532367f0f91aee/lua/nvim-tree/explorer/watch.lua#L43-L45))
- update all callers to check first if the node is in `M.ignored_paths` before calling `create_watcher`

What's your thought?

[the remark this answers is not in the document]
Comment (alex-courtis) [reply lua/nvim-tree/git/init.lua:167]: > However, `create_watcher` still have too much responsibility to me.

That is sensible. `is_git` is doing too much, as well as being broken.

[the remark this answers is not in the document]
Comment (alex-courtis) [reply lua/nvim-tree/git/init.lua:167]: > the caller check if the node is part of the config

That could be tricky, as there are many call sites.

Adding to the ignored list as per https://github.com/nvim-tree/nvim-tree.lua/pull/2012/files#diff-6e591951880a9ff855ceca8fb5a150c85deeb19593cd5143ed8b19a125f0f9e7R166 does seem to be the right way to go. The git project is loaded before enumerating the tree so the git directory will be in the `ignore_dirs`. I'll document that assumption.

Filtering `IGNORED_PATHS` and `ignore_dirs` is thus Good Enough. The current solution does that.

Let's be safe and not mutate config:
1. `watch.lua` setup copies `filesystem_watchers.ignore_dirs` into `M.ignore_dirs` 
2. create `M.ignore_dir(path)` in `watch.lua` that adds to `M.ignore_dirs`
3. `load_project_status` calls `watch.ignore_dir(base_gitdir)`

[the remark this answers is not in the document]
Comment (alex-courtis) [reply lua/nvim-tree/git/init.lua:167]: Testing in a variety of situations (mostly flipping around directories, reloading) shows that `load_project_status` is (always?) run before creating regular filesystem watchers. This will prevent any unwanted watchers.

Even if we do end up creating extra watchers, it's not such a big drama; we are already doing that when the git directory is opened.

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Please:

- [ ] @dmehala Tidy watch.lua https://github.com/nvim-tree/nvim-tree.lua/pull/2012#discussion_r1125803634
- [ ] @dmehala Remove unnecessary git call https://github.com/nvim-tree/nvim-tree.lua/pull/2012/files#r1125590684
- [ ] @alex-courtis Document assumptions

**Comment by alex-courtis** [comment]
Any updates on this one @dmehala ?

**Comment by dmehala** [comment]
Hey @alex-courtis,

Sorry for the late reply, I think I've manage to follow your requirements. May you have a look? :)

**Comment by alex-courtis** [comment]
Experimental async git status handling has been added #2104

Please do test this.

I am dogfooding this branch, with async enabled for ~week.

**Comment by gegoune** [comment]
I have been using it for a while, didn't notice any issues.

**Review by alex-courtis — APPROVED** [review]
Many thanks for your contribution @dmehala !
